using Yaat.Sim.Commands;

namespace Yaat.Client.Services;

public static class CommandMetadata
{
    public record CommandInfo(CanonicalCommandType Type, string Label, string? SampleArg, bool IsGlobal, string Category);

    public static readonly IReadOnlyList<CommandInfo> AllCommands =
    [
        // Heading
        new(CanonicalCommandType.FlyHeading, "Fly Heading", "270", false, "Heading"),
        new(CanonicalCommandType.TurnLeft, "Turn Left", "270", false, "Heading"),
        new(CanonicalCommandType.TurnRight, "Turn Right", "090", false, "Heading"),
        new(CanonicalCommandType.RelativeLeft, "Relative Left", "20", false, "Heading"),
        new(CanonicalCommandType.RelativeRight, "Relative Right", "30", false, "Heading"),
        new(CanonicalCommandType.FlyPresentHeading, "Fly Present Heading", null, false, "Heading"),
        // Altitude / Speed
        new(CanonicalCommandType.ClimbMaintain, "Climb/Maintain", "240", false, "Altitude / Speed"),
        new(CanonicalCommandType.DescendMaintain, "Descend/Maintain", "50", false, "Altitude / Speed"),
        new(CanonicalCommandType.Speed, "Speed", "250", false, "Altitude / Speed"),
        // Transponder
        new(CanonicalCommandType.Squawk, "Squawk", "1234", false, "Transponder"),
        new(CanonicalCommandType.SquawkVfr, "Squawk VFR", null, false, "Transponder"),
        new(CanonicalCommandType.SquawkNormal, "Squawk Normal", null, false, "Transponder"),
        new(CanonicalCommandType.SquawkStandby, "Squawk Standby", null, false, "Transponder"),
        new(CanonicalCommandType.Ident, "Ident", null, false, "Transponder"),
        new(CanonicalCommandType.RandomSquawk, "Random Squawk", null, false, "Transponder"),
        new(CanonicalCommandType.SquawkAll, "Squawk All", null, true, "Transponder"),
        new(CanonicalCommandType.SquawkNormalAll, "Squawk Normal All", null, true, "Transponder"),
        new(CanonicalCommandType.SquawkStandbyAll, "Squawk Standby All", null, true, "Transponder"),
        // Navigation
        new(CanonicalCommandType.DirectTo, "Direct To", "FIX", false, "Navigation"),
        new(CanonicalCommandType.ForceDirectTo, "Force Direct To Fix", "FIX", false, "Navigation"),
        new(CanonicalCommandType.AppendDirectTo, "Append Direct To", "FIX", false, "Navigation"),
        // Tower
        new(CanonicalCommandType.LineUpAndWait, "Line Up and Wait", null, false, "Tower"),
        new(CanonicalCommandType.ClearedForTakeoff, "Cleared for Takeoff", "RH", false, "Tower"),
        new(CanonicalCommandType.CancelTakeoffClearance, "Cancel Takeoff Clearance", null, false, "Tower"),
        new(CanonicalCommandType.GoAround, "Go Around", "270", false, "Tower"),
        new(CanonicalCommandType.ClearedToLand, "Cleared to Land", null, false, "Tower"),
        new(CanonicalCommandType.CancelLandingClearance, "Cancel Landing Clearance", null, false, "Tower"),
        new(CanonicalCommandType.TouchAndGo, "Touch and Go", null, false, "Tower"),
        new(CanonicalCommandType.StopAndGo, "Stop and Go", null, false, "Tower"),
        new(CanonicalCommandType.LowApproach, "Low Approach", null, false, "Tower"),
        new(CanonicalCommandType.ClearedForOption, "Cleared for the Option", null, false, "Tower"),
        // Pattern
        new(CanonicalCommandType.EnterLeftDownwind, "Enter Left Downwind", "28R", false, "Pattern"),
        new(CanonicalCommandType.EnterRightDownwind, "Enter Right Downwind", "28R", false, "Pattern"),
        new(CanonicalCommandType.EnterLeftBase, "Enter Left Base", "28R 3", false, "Pattern"),
        new(CanonicalCommandType.EnterRightBase, "Enter Right Base", "28R 3", false, "Pattern"),
        new(CanonicalCommandType.EnterFinal, "Enter Final", "28R", false, "Pattern"),
        new(CanonicalCommandType.MakeLeftTraffic, "Make Left Traffic", null, false, "Pattern"),
        new(CanonicalCommandType.MakeRightTraffic, "Make Right Traffic", null, false, "Pattern"),
        new(CanonicalCommandType.TurnCrosswind, "Turn Crosswind", null, false, "Pattern"),
        new(CanonicalCommandType.TurnDownwind, "Turn Downwind", null, false, "Pattern"),
        new(CanonicalCommandType.TurnBase, "Turn Base", null, false, "Pattern"),
        new(CanonicalCommandType.ExtendDownwind, "Extend Downwind", null, false, "Pattern"),
        new(CanonicalCommandType.MakeShortApproach, "Make Short Approach", null, false, "Pattern"),
        new(CanonicalCommandType.MakeLeft360, "Make Left 360", null, false, "Pattern"),
        new(CanonicalCommandType.MakeRight360, "Make Right 360", null, false, "Pattern"),
        new(CanonicalCommandType.MakeLeft270, "Make Left 270", null, false, "Pattern"),
        new(CanonicalCommandType.MakeRight270, "Make Right 270", null, false, "Pattern"),
        new(CanonicalCommandType.CircleAirport, "Circle Airport", null, false, "Pattern"),
        new(CanonicalCommandType.Sequence, "Landing Sequence", "2 UAL123", false, "Tower"),
        // Hold
        new(CanonicalCommandType.HoldPresentPosition360Left, "Hold (360 Left)", null, false, "Hold"),
        new(CanonicalCommandType.HoldPresentPosition360Right, "Hold (360 Right)", null, false, "Hold"),
        new(CanonicalCommandType.HoldPresentPositionHover, "Hold Present Position", null, false, "Hold"),
        new(CanonicalCommandType.HoldAtFixLeft, "Hold at Fix (Left)", "FIX", false, "Hold"),
        new(CanonicalCommandType.HoldAtFixRight, "Hold at Fix (Right)", "FIX", false, "Hold"),
        new(CanonicalCommandType.HoldAtFixHover, "Hold at Fix", "FIX", false, "Hold"),
        // Helicopter
        new(CanonicalCommandType.AirTaxi, "Air Taxi", "H1", false, "Helicopter"),
        new(CanonicalCommandType.Land, "Land", "H1", false, "Helicopter"),
        new(CanonicalCommandType.ClearedTakeoffPresent, "Cleared Takeoff Present Position", null, false, "Helicopter"),
        // Ground
        new(CanonicalCommandType.Pushback, "Pushback", "270", false, "Ground"),
        new(CanonicalCommandType.Taxi, "Taxi", "S T U W W1", false, "Ground"),
        new(CanonicalCommandType.HoldPosition, "Hold Position", null, false, "Ground"),
        new(CanonicalCommandType.Resume, "Resume Taxi", null, false, "Ground"),
        new(CanonicalCommandType.CrossRunway, "Cross Runway", "28L", false, "Ground"),
        new(CanonicalCommandType.HoldShort, "Hold Short", "B", false, "Ground"),
        new(CanonicalCommandType.Follow, "Follow", "SWA123", false, "Ground"),
        new(CanonicalCommandType.ExitLeft, "Exit Left", null, false, "Ground"),
        new(CanonicalCommandType.ExitRight, "Exit Right", null, false, "Ground"),
        new(CanonicalCommandType.ExitTaxiway, "Exit Taxiway", "A3", false, "Ground"),
        // Sim control
        new(CanonicalCommandType.Delete, "Delete", null, false, "Sim Control"),
        new(CanonicalCommandType.Pause, "Pause", null, true, "Sim Control"),
        new(CanonicalCommandType.Unpause, "Unpause", null, true, "Sim Control"),
        new(CanonicalCommandType.SimRate, "Sim Rate", "2", true, "Sim Control"),
        new(CanonicalCommandType.Wait, "Wait (seconds)", "30", false, "Sim Control"),
        new(CanonicalCommandType.WaitDistance, "Wait (distance)", "4", false, "Sim Control"),
        new(CanonicalCommandType.Add, "Add Aircraft", "IFR H J -270 15 10000", true, "Sim Control"),
        new(CanonicalCommandType.SpawnNow, "Spawn Now", null, false, "Sim Control"),
        new(CanonicalCommandType.SpawnDelay, "Set Spawn Delay", "120", false, "Sim Control"),
        // Track operations
        new(CanonicalCommandType.SetActivePosition, "Act As Position", "2B", true, "Track Operations"),
        new(CanonicalCommandType.TrackAircraft, "Track", null, false, "Track Operations"),
        new(CanonicalCommandType.DropTrack, "Drop Track", null, false, "Track Operations"),
        new(CanonicalCommandType.InitiateHandoff, "Handoff", "2B", false, "Track Operations"),
        new(CanonicalCommandType.AcceptHandoff, "Accept Handoff", null, false, "Track Operations"),
        new(CanonicalCommandType.CancelHandoff, "Cancel Handoff", null, false, "Track Operations"),
        new(CanonicalCommandType.AcceptAllHandoffs, "Accept All Handoffs", null, true, "Track Operations"),
        new(CanonicalCommandType.InitiateHandoffAll, "Handoff All", "2B", true, "Track Operations"),
        new(CanonicalCommandType.PointOut, "Point Out", "2B", false, "Track Operations"),
        new(CanonicalCommandType.Acknowledge, "Acknowledge", null, false, "Track Operations"),
        // Data operations
        new(CanonicalCommandType.Annotate, "Annotate", null, false, "Data Operations"),
        new(CanonicalCommandType.Scratchpad, "Scratchpad", "VFR", false, "Data Operations"),
        new(CanonicalCommandType.TemporaryAltitude, "Temporary Altitude", "40", false, "Data Operations"),
        new(CanonicalCommandType.Cruise, "Cruise Altitude", "240", false, "Data Operations"),
        new(CanonicalCommandType.FrequencyChange, "Frequency Change", null, false, "Data Operations"),
        new(CanonicalCommandType.ContactTcp, "Contact Position", "2B", false, "Data Operations"),
        new(CanonicalCommandType.ContactTower, "Contact Tower", null, false, "Data Operations"),
        new(CanonicalCommandType.OnHandoff, "On Handoff", null, false, "Track Operations"),
        // Coordination
        new(CanonicalCommandType.CoordinationRelease, "Release (Rundown)", "POAK", false, "Coordination"),
        new(CanonicalCommandType.CoordinationHold, "Hold Release", "POAK", false, "Coordination"),
        new(CanonicalCommandType.CoordinationRecall, "Recall Release", "POAK", false, "Coordination"),
        new(CanonicalCommandType.CoordinationAcknowledge, "Acknowledge Release", "POAK", false, "Coordination"),
        new(CanonicalCommandType.CoordinationAutoAck, "Toggle Auto-Ack", "POAK", true, "Coordination"),
        // Broadcast
        new(CanonicalCommandType.Say, "Say", "REQUEST VFR TRANSITION", false, "Broadcast"),
        // Approach
        new(CanonicalCommandType.ExpectApproach, "Expect Approach", "I28R", false, "Approach"),
        new(CanonicalCommandType.ClearedApproach, "Cleared Approach", "ILS28R", false, "Approach"),
        new(CanonicalCommandType.JoinApproach, "Join Approach", "ILS28R", false, "Approach"),
        new(CanonicalCommandType.ClearedApproachStraightIn, "Cleared Straight-In", "ILS28R", false, "Approach"),
        new(CanonicalCommandType.JoinApproachStraightIn, "Join Straight-In", "ILS28R", false, "Approach"),
        new(CanonicalCommandType.ClearedApproachForce, "Cleared Approach (Force)", "ILS28R", false, "Approach"),
        new(CanonicalCommandType.JoinApproachForce, "Join Approach (Force)", "ILS28R", false, "Approach"),
        new(CanonicalCommandType.JoinFinalApproachCourse, "Join Final Approach Course", "ILS28R", false, "Approach"),
        new(CanonicalCommandType.JoinStar, "Join STAR", "SUNOL1 KENNO", false, "Approach"),
        new(CanonicalCommandType.JoinRadialOutbound, "Join Radial Outbound", "OAK090", false, "Approach"),
        new(CanonicalCommandType.JoinRadialInbound, "Join Radial Inbound", "OAK090", false, "Approach"),
        new(CanonicalCommandType.HoldingPattern, "Holding Pattern", "SUNOL 090 3 R", false, "Approach"),
        new(CanonicalCommandType.PositionTurnAltitudeClearance, "PTAC", "280 025 ILS30", false, "Approach"),
        new(CanonicalCommandType.ClimbVia, "Climb Via", "190", false, "Approach"),
        new(CanonicalCommandType.DescendVia, "Descend Via", "40", false, "Approach"),
        new(CanonicalCommandType.CrossFix, "Cross Fix", "SUNOL A040", false, "Approach"),
        new(CanonicalCommandType.DepartFix, "Depart Fix", "SUNOL 270", false, "Approach"),
        new(CanonicalCommandType.ListApproaches, "List Approaches", "OAK", true, "Approach"),
        new(CanonicalCommandType.ClearedVisualApproach, "Cleared Visual Approach", "28R", false, "Approach"),
        new(CanonicalCommandType.ReportFieldInSight, "Report Field In Sight", "", true, "Approach"),
        new(CanonicalCommandType.ReportTrafficInSight, "Report Traffic In Sight", "AAL123", true, "Approach"),
    ];
}
