using Microsoft.Extensions.Logging;
using Xunit;
using Xunit.Abstractions;
using Yaat.Sim.Phases;
using Yaat.Sim.Phases.Ground;
using Yaat.Sim.Phases.Tower;
using Yaat.Sim.Simulation;
using Yaat.Sim.Tests.Helpers;

namespace Yaat.Sim.Tests.Simulation;

/// <summary>
/// E2E tests for the "PCM8702 didn't depart 28L, it was stuck" report from the
/// S2-OAK-5 (2) Practical Exam Preparation/Advanced Concepts bundle.
///
/// PCM8702 (C208) departs OAK 28L. Preset: <c>PUSH R1</c>; <c>WAIT 54 TAXI R1 R B1 B 28L</c>.
/// Recorded controller commands: <c>CTO @ t=197</c>, <c>LUAW @ t=251</c>, <c>DEL @ t=267</c>.
/// The bundle's snapshots (regenerated by deterministic replay at export) show PCM8702
/// lining up and departing cleanly (airborne ~t=240). But the user issued LUAW at t=251 —
/// when the replay shows the aircraft already climbing through ~283 ft — then deleted it,
/// which only makes sense if it was stuck on the ground live.
///
/// These two probes exercise the *current* code:
///   1. <see cref="ScenarioRun_PcmDepartsAfterCto"/> — loads the exact scenario + seed, ticks
///      forward so the presets taxi PCM8702 to hold short of 28L, issues CTO at that moment,
///      and asserts it actually departs (reaches Takeoff/InitialClimb and rolls).
///   2. <see cref="Replay_PcmDepartsAfterRecordedCto"/> — faithfully replays the recorded
///      action log (all traffic + commands) through the recorded CTO and asserts PCM8702
///      advances past LineUp before the recorded DEL removes it.
///
/// If either reproduces the stuck, that's a deterministic bug to fix. If both depart PCM
/// cleanly, the stuck is the live-only mid-physics command race (per
/// docs/plans/command-tick-synchronization.md, Part 2) which deterministic replay can't show.
/// </summary>
public class Issue2Pcm28LStuckTests
{
    private const string BundlePath = "TestData/issue2-pcm-28l-stuck-recording.yaat-bug-report-bundle.zip";
    private const string Callsign = "PCM8702";

    private readonly ITestOutputHelper output;

    public Issue2Pcm28LStuckTests(ITestOutputHelper output)
    {
        this.output = output;
        // Pin singletons before any [Fact] body runs (parallel-class race guard).
        TestVnasData.EnsureInitialized();
    }

    private SimulationEngine? BuildEngine()
    {
        if (TestVnasData.NavigationDb is null)
        {
            return null;
        }

        var groundData = new TestAirportGroundData();
        if (groundData.GetLayout("OAK") is null)
        {
            return null;
        }

        SimLogBuilder
            .CreateForTest(output)
            .EnableCategory("LineUpPhase", LogLevel.Debug)
            .EnableCategory("TakeoffPhase", LogLevel.Debug)
            .EnableCategory("HoldingShortPhase", LogLevel.Debug)
            .EnableCategory("GroundConflictDetector", LogLevel.Debug)
            .InitializeSimLog();

        return new SimulationEngine(groundData);
    }

    /// <summary>
    /// User's steer: load the exact scenario, let the engine run until PCM8702 is holding
    /// short of 28L, issue CTO, and verify it departs. No recorded controller commands are
    /// applied — only the scenario presets drive the taxi-out.
    /// </summary>
    [Fact]
    public void ScenarioRun_PcmDepartsAfterCto()
    {
        var recording = RecordingLoader.Load(BundlePath);
        var engine = BuildEngine();
        if (recording is null || engine is null)
        {
            return;
        }

        // Replay(_, 0) loads scenario + weather + ARTCC config and queues presets, but applies
        // no recorded actions; the TickOneSecond loop below fires the presets (PUSH, timed TAXI).
        engine.Replay(recording, 0);

        // Tick until PCM8702 is holding short of 28L (preset taxi-out). Budget generously.
        const int taxiBudget = 600;
        int holdingShortAt = -1;
        for (int t = 1; t <= taxiBudget; t++)
        {
            engine.TickOneSecond();
            var ac = engine.FindAircraft(Callsign);
            if (ac is null)
            {
                continue;
            }

            if (IsHoldingShortOf(ac, "28L"))
            {
                holdingShortAt = t;
                output.WriteLine($"t={t}: {Callsign} holding short of 28L ({Describe(ac)})");
                break;
            }

            if (t % 20 == 0)
            {
                output.WriteLine($"t={t}: {Describe(ac)}");
            }
        }

        var atHold = engine.FindAircraft(Callsign);
        Assert.NotNull(atHold);
        Assert.True(holdingShortAt > 0, $"{Callsign} never reached HoldingShort of 28L within {taxiBudget}s. Last state: {Describe(atHold)}");

        // Issue CTO at the moment it is holding short (mirrors the controller's t=197 CTO).
        var result = engine.SendCommand(Callsign, "CTO");
        output.WriteLine($"CTO -> Success={result.Success} Message=\"{result.Message}\"");
        Assert.True(result.Success, $"CTO rejected: {result.Message}");

        // Tick forward and watch for an actual departure.
        const int departBudget = 180;
        bool departed = false;
        for (int t = 1; t <= departBudget; t++)
        {
            engine.TickOneSecond();
            var ac = engine.FindAircraft(Callsign);
            Assert.NotNull(ac);

            if (t % 5 == 0 || ac.Phases?.CurrentPhase is TakeoffPhase or InitialClimbPhase)
            {
                output.WriteLine($"CTO+{t}: {Describe(ac)}");
            }

            if (HasDeparted(ac))
            {
                departed = true;
                output.WriteLine($"CTO+{t}: DEPARTED — {Describe(ac)}");
                break;
            }
        }

        var final = engine.FindAircraft(Callsign);
        Assert.True(
            departed,
            $"{Callsign} never departed within {departBudget}s of CTO — stuck. " + $"Final state: {(final is null ? "(removed)" : Describe(final))}"
        );
    }

    /// <summary>
    /// Faithful replay of the recorded action log (all traffic + controller commands).
    /// Steps from just before the recorded CTO (t=197) to just before the recorded DEL
    /// (t=267) and asserts PCM8702 leaves the ground rather than sitting in LineUp.
    /// </summary>
    [Fact]
    public void Replay_PcmDepartsAfterRecordedCto()
    {
        var recording = RecordingLoader.Load(BundlePath);
        var engine = BuildEngine();
        if (recording is null || engine is null)
        {
            return;
        }

        engine.Replay(recording, 190);

        var ac = engine.FindAircraft(Callsign);
        Assert.NotNull(ac);
        output.WriteLine($"t=190: {Describe(ac)}");

        // CTO is recorded at t=197; DEL at t=267. Watch the window in between.
        bool departed = false;
        for (int t = 191; t <= 266; t++)
        {
            engine.ReplayOneSecond();
            ac = engine.FindAircraft(Callsign);
            if (ac is null)
            {
                output.WriteLine($"t={t}: {Callsign} no longer present");
                break;
            }

            if (t % 5 == 0 || ac.Phases?.CurrentPhase is TakeoffPhase or InitialClimbPhase)
            {
                output.WriteLine($"t={t}: {Describe(ac)}");
            }

            if (HasDeparted(ac))
            {
                departed = true;
                output.WriteLine($"t={t}: DEPARTED — {Describe(ac)}");
                break;
            }
        }

        var final = engine.FindAircraft(Callsign);
        Assert.True(
            departed,
            $"{Callsign} never departed in the recorded CTO window (t=197..266) — stuck. "
                + $"Final state: {(final is null ? "(removed)" : Describe(final))}"
        );
    }

    private static bool IsHoldingShortOf(AircraftState ac, string runway) =>
        ac.Phases?.CurrentPhase is HoldingShortPhase hsp
        && hsp.HoldShort.TargetName is { } target
        && target.Contains(runway, StringComparison.OrdinalIgnoreCase);

    private static bool HasDeparted(AircraftState ac) =>
        ac.Phases?.CurrentPhase is TakeoffPhase or InitialClimbPhase || (!ac.IsOnGround && ac.IndicatedAirspeed > 40);

    private static string Describe(AircraftState ac)
    {
        string phase = ac.Phases?.CurrentPhase?.GetType().Name ?? "(null)";
        string chain = ac.Phases is null
            ? "(null)"
            : string.Join(" -> ", ac.Phases.Phases.Select((p, i) => i == ac.Phases.CurrentIndex ? $"[{p.GetType().Name}]" : p.GetType().Name));
        string speedLimit = ac.Ground.SpeedLimit is { } sl ? sl.ToString("F1") : "-";
        return $"phase={phase} ias={ac.IndicatedAirspeed:F1} alt={ac.Altitude:F0} vs={ac.VerticalSpeed:F0} onGround={ac.IsOnGround} spdLim={speedLimit} chain={chain}";
    }
}
