namespace Yaat.Sim.Commands;

public enum CanonicalCommandType
{
    FlyHeading,
    TurnLeft,
    TurnRight,
    RelativeLeft,
    RelativeRight,
    FlyPresentHeading,
    ClimbMaintain,
    DescendMaintain,
    Speed,
    Squawk,
    SquawkVfr,
    SquawkNormal,
    SquawkStandby,
    Ident,
    RandomSquawk,
    SquawkAll,
    SquawkNormalAll,
    SquawkStandbyAll,
    DirectTo,
    AppendDirectTo,
    Delete,
    Pause,
    Unpause,
    SimRate,
    Wait,
    WaitDistance,
    LineUpAndWait,
    ClearedForTakeoff,
    CancelTakeoffClearance,
    GoAround,
    ClearedToLand,
    CancelLandingClearance,
    TouchAndGo,
    StopAndGo,
    LowApproach,
    ClearedForOption,

    // Pattern commands
    EnterLeftDownwind,
    EnterRightDownwind,
    EnterLeftBase,
    EnterRightBase,
    EnterFinal,
    MakeLeftTraffic,
    MakeRightTraffic,
    TurnCrosswind,
    TurnDownwind,
    TurnBase,
    ExtendDownwind,
    MakeShortApproach,
    MakeLeft360,
    MakeRight360,
    MakeLeft270,
    MakeRight270,
    CircleAirport,
    Sequence,

    // Hold commands
    HoldPresentPosition360Left,
    HoldPresentPosition360Right,
    HoldPresentPositionHover,
    HoldAtFixLeft,
    HoldAtFixRight,
    HoldAtFixHover,

    // Ground commands
    Pushback,
    Taxi,
    HoldPosition,
    Resume,
    CrossRunway,
    HoldShort,
    Follow,
    ExitLeft,
    ExitRight,
    ExitTaxiway,

    // Spawn control
    Add,
    SpawnNow,
    SpawnDelay,

    // Track operations
    SetActivePosition,
    TrackAircraft,
    DropTrack,
    InitiateHandoff,
    AcceptHandoff,
    CancelHandoff,
    AcceptAllHandoffs,
    InitiateHandoffAll,
    PointOut,
    Acknowledge,
    Annotate,
    Scratchpad,
    TemporaryAltitude,
    Cruise,
    OnHandoff,
    FrequencyChange,
    ContactTcp,
    ContactTower,

    // Coordination
    CoordinationRelease,
    CoordinationHold,
    CoordinationRecall,
    CoordinationAcknowledge,
    CoordinationAutoAck,

    // Broadcast
    Say,
}
