namespace Yaat.Sim.Commands;

public enum CanonicalCommandType
{
    FlyHeading,
    TurnLeft,
    TurnRight,
    RelativeLeft,
    RelativeRight,
    FlyPresentHeading,
    ClimbMaintain,
    DescendMaintain,
    Speed,
    Squawk,
    SquawkIdent,
    SquawkVfr,
    SquawkNormal,
    SquawkStandby,
    Ident,
    DirectTo,
    Delete,
    Pause,
    Unpause,
    SimRate,
    LineUpAndWait,
    ClearedForTakeoff,
    CancelTakeoffClearance,
    GoAround,
    ClearedToLand,
    TouchAndGo,
    StopAndGo,
    LowApproach,
    ClearedForOption,
    // Pattern commands
    EnterLeftDownwind,
    EnterRightDownwind,
    EnterLeftBase,
    EnterRightBase,
    EnterFinal,
    MakeLeftTraffic,
    MakeRightTraffic,
    TurnCrosswind,
    TurnDownwind,
    TurnBase,
    ExtendDownwind,
    // Hold commands
    HoldPresentPosition360Left,
    HoldPresentPosition360Right,
    HoldPresentPositionHover,
    HoldAtFixLeft,
    HoldAtFixRight,
    HoldAtFixHover,
}
