using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;

namespace Yaat.Sim.Data;

/// <summary>
/// Maps ACD-known ICAO type codes that lack an <see cref="AircraftProfile"/> to a
/// curated sibling that does have one. Generated by <c>tools/build_aircraft_sibling_map.py</c>
/// and shipped as <c>Data/AircraftProfileSiblings.json</c>. Consulted on miss by
/// <see cref="AircraftProfileDatabase"/>, <see cref="Yaat.Sim.Data.Faa.FaaAircraftDatabase"/>,
/// and <see cref="AircraftCategorization"/> so types we don't have profiles for fall back
/// to a close match (e.g. <c>B789 -&gt; B788</c>) instead of silently sliding to
/// category-default Jet performance.
///
/// Manual overrides (in the script) also handle informal aliases (e.g. <c>PA28 -&gt; P28A</c>).
/// </summary>
public static class AircraftSiblingMap
{
    private static readonly ILogger Log = SimLog.CreateLogger("AircraftSiblingMap");

    private static Dictionary<string, string> _lookup = new(StringComparer.OrdinalIgnoreCase);

    public static bool IsInitialized => _lookup.Count > 0;

    public static int Count => _lookup.Count;

    public static void Initialize(Dictionary<string, string> lookup)
    {
        _lookup = new Dictionary<string, string>(lookup, StringComparer.OrdinalIgnoreCase);
        Log.LogInformation("Aircraft sibling map loaded: {Count} entries", _lookup.Count);
    }

    /// <summary>
    /// Try to resolve <paramref name="aircraftType"/> to a sibling type code.
    /// Returns false if no sibling is registered. The caller is responsible for
    /// looking up the sibling in the appropriate database.
    /// </summary>
    public static bool TryResolve(string? aircraftType, out string sibling)
    {
        if (!string.IsNullOrEmpty(aircraftType) && _lookup.TryGetValue(aircraftType, out var sib))
        {
            sibling = sib;
            return true;
        }
        sibling = string.Empty;
        return false;
    }

    /// <summary>
    /// Load a sibling map from the JSON file produced by
    /// <c>tools/build_aircraft_sibling_map.py</c>.
    /// </summary>
    public static Dictionary<string, string> LoadFromFile(string path)
    {
        var json = File.ReadAllText(path);
        var doc =
            JsonSerializer.Deserialize<SiblingMapDocument>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
            ?? throw new InvalidOperationException($"Failed to deserialize aircraft sibling map from {path}");

        var result = new Dictionary<string, string>(doc.Siblings.Count, StringComparer.OrdinalIgnoreCase);
        foreach (var (missing, entry) in doc.Siblings)
        {
            if (!string.IsNullOrEmpty(entry.Sibling))
            {
                result[missing] = entry.Sibling;
            }
        }
        return result;
    }

    private sealed class SiblingMapDocument
    {
        [JsonPropertyName("siblings")]
        public Dictionary<string, SiblingEntry> Siblings { get; set; } = new();
    }

    private sealed class SiblingEntry
    {
        [JsonPropertyName("sibling")]
        public string Sibling { get; set; } = string.Empty;

        [JsonPropertyName("source")]
        public string Source { get; set; } = string.Empty;
    }
}
