using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using Microsoft.Extensions.Logging;

namespace Yaat.Sim.Data;

/// <summary>
/// Static map between airline ICAO codes and the ICAO Doc 8643 aircraft type
/// designators they operate, with aircraft counts per type.
///
/// Data source: Airfleets World Fleet Listing (paid quarterly publication). The
/// canonical JSON file is regenerated by <c>tools/refresh-airline-fleets.py</c>;
/// see <c>docs/airline-fleets.md</c> for the refresh procedure.
/// </summary>
/// <remarks>
/// Both lookup directions are pre-computed and exposed:
///   <list type="bullet">
///     <item><see cref="TryGetAirline"/> — given an airline ICAO, returns its fleet.</item>
///     <item><see cref="TryGetAirlinesForType"/> — given an aircraft ICAO type, returns the airlines that operate it.</item>
///   </list>
/// Counts reflect the number of airframes at the time the source publication
/// was assembled. Treat as a snapshot (months-old at refresh time, drifts as
/// fleets evolve), not as live data.
/// </remarks>
public static class AirlineFleets
{
    private static readonly ILogger Log = SimLog.CreateLogger("AirlineFleets");

    private static readonly Lazy<Data> _data = new(Load, LazyThreadSafetyMode.ExecutionAndPublication);

    /// <summary>Number of airlines covered by the map. Forces initialization.</summary>
    public static int AirlineCount => _data.Value.ByAirline.Count;

    /// <summary>Number of distinct ICAO aircraft types appearing in the map.</summary>
    public static int TypeCount => _data.Value.ByType.Count;

    /// <summary>Human-readable source description, e.g. "Airfleets World Fleet Listing Issue 123".</summary>
    public static string SourceDescription => _data.Value.SourceDescription;

    /// <summary>Source publication date as ISO-8601 (YYYY-MM-DD), or empty if unknown.</summary>
    public static string SourceDate => _data.Value.SourceDate;

    /// <summary>Look up an airline's fleet by ICAO code (case-insensitive).</summary>
    /// <param name="airlineIcao">3-letter ICAO airline code.</param>
    /// <param name="info">Airline name, country, and per-type aircraft counts.</param>
    public static bool TryGetAirline(string airlineIcao, [NotNullWhen(true)] out AirlineFleetInfo? info)
    {
        if (string.IsNullOrWhiteSpace(airlineIcao))
        {
            info = null;
            return false;
        }
        return _data.Value.ByAirline.TryGetValue(airlineIcao.ToUpperInvariant(), out info);
    }

    /// <summary>Convenience: just the type-to-count map for an airline.</summary>
    public static bool TryGetTypes(string airlineIcao, [NotNullWhen(true)] out IReadOnlyDictionary<string, int>? types)
    {
        if (TryGetAirline(airlineIcao, out var info))
        {
            types = info.Types;
            return true;
        }
        types = null;
        return false;
    }

    /// <summary>Reverse lookup: which airlines operate the given aircraft type, and how many of each.</summary>
    /// <param name="typeIcao">ICAO Doc 8643 aircraft type designator (e.g. B38M, A21N, BCS3).</param>
    /// <param name="airlines">Map of airline ICAO -> aircraft count.</param>
    public static bool TryGetAirlinesForType(string typeIcao, [NotNullWhen(true)] out IReadOnlyDictionary<string, int>? airlines)
    {
        if (string.IsNullOrWhiteSpace(typeIcao))
        {
            airlines = null;
            return false;
        }
        return _data.Value.ByType.TryGetValue(typeIcao.ToUpperInvariant(), out airlines);
    }

    /// <summary>True if the given airline is recorded as operating the given aircraft type (≥1 airframe).</summary>
    public static bool Operates(string airlineIcao, string typeIcao)
    {
        return TryGetTypes(airlineIcao, out var types) && types.ContainsKey(typeIcao.ToUpperInvariant());
    }

    /// <summary>All airline ICAOs in the map, in insertion order (alphabetical from generator).</summary>
    public static IEnumerable<string> AllAirlineIcaos() => _data.Value.ByAirline.Keys;

    /// <summary>All aircraft type ICAOs in the map, in insertion order (alphabetical from generator).</summary>
    public static IEnumerable<string> AllTypeIcaos() => _data.Value.ByType.Keys;

    private static Data Load()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Data", "airline-fleets.json");
        if (!File.Exists(path))
        {
            Log.LogWarning("airline-fleets.json not found at {Path}; airline-fleet map will be empty", path);
            return Data.Empty;
        }

        try
        {
            using var stream = File.OpenRead(path);
            var root = JsonSerializer.Deserialize<JsonRoot>(stream, JsonOptions);
            if (root is null)
            {
                Log.LogWarning("airline-fleets.json at {Path} deserialized to null; map will be empty", path);
                return Data.Empty;
            }

            var byAirline = new Dictionary<string, AirlineFleetInfo>(StringComparer.OrdinalIgnoreCase);
            foreach (var (icao, entry) in root.ByAirline ?? [])
            {
                if (string.IsNullOrWhiteSpace(icao) || entry is null)
                {
                    continue;
                }

                var types = entry.Types ?? new Dictionary<string, int>();
                byAirline[icao.ToUpperInvariant()] = new AirlineFleetInfo(
                    icao.ToUpperInvariant(),
                    entry.Name ?? "",
                    entry.Country ?? "",
                    new Dictionary<string, int>(types, StringComparer.OrdinalIgnoreCase)
                );
            }

            var byType = new Dictionary<string, IReadOnlyDictionary<string, int>>(StringComparer.OrdinalIgnoreCase);
            foreach (var (typeIcao, airlines) in root.ByType ?? [])
            {
                if (string.IsNullOrWhiteSpace(typeIcao) || airlines is null)
                {
                    continue;
                }

                byType[typeIcao.ToUpperInvariant()] = new Dictionary<string, int>(airlines, StringComparer.OrdinalIgnoreCase);
            }

            var source = root.Metadata?.Source ?? "";
            var sourceDate = root.Metadata?.SourceDate ?? "";

            Log.LogInformation(
                "Loaded {AirlineCount} airlines / {TypeCount} aircraft types from {Source} ({Date})",
                byAirline.Count,
                byType.Count,
                source,
                sourceDate
            );

            return new Data(source, sourceDate, byAirline, byType);
        }
        catch (Exception ex)
        {
            Log.LogError(ex, "Failed to load airline-fleets.json from {Path}; map will be empty", path);
            return Data.Empty;
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        PropertyNameCaseInsensitive = true,
    };

    private sealed record Data(
        string SourceDescription,
        string SourceDate,
        IReadOnlyDictionary<string, AirlineFleetInfo> ByAirline,
        IReadOnlyDictionary<string, IReadOnlyDictionary<string, int>> ByType
    )
    {
        public static readonly Data Empty = new(
            "",
            "",
            new Dictionary<string, AirlineFleetInfo>(),
            new Dictionary<string, IReadOnlyDictionary<string, int>>()
        );
    }

    private sealed class JsonRoot
    {
        public JsonMetadata? Metadata { get; set; }
        public Dictionary<string, JsonAirlineEntry>? ByAirline { get; set; }
        public Dictionary<string, Dictionary<string, int>>? ByType { get; set; }
    }

    private sealed class JsonMetadata
    {
        public string? Source { get; set; }
        public string? SourceDate { get; set; }
        public string? GeneratedUtc { get; set; }
    }

    private sealed class JsonAirlineEntry
    {
        public string? Name { get; set; }
        public string? Country { get; set; }
        public Dictionary<string, int>? Types { get; set; }
    }
}

/// <summary>
/// One airline's fleet snapshot: name, country, and the count of airframes per
/// ICAO Doc 8643 aircraft type.
/// </summary>
public sealed record AirlineFleetInfo(string Icao, string Name, string Country, IReadOnlyDictionary<string, int> Types);
