using System.Diagnostics.CodeAnalysis;
using System.IO.Compression;
using System.Text.Json;
using Microsoft.Extensions.Logging;

namespace Yaat.Sim.Data;

/// <summary>
/// Static airport -> served-airline lookup used by arrival generators to pick
/// airlines that plausibly operate into the scenario airport.
///
/// The checked-in fixture is generated by <c>tools/refresh-airport-airlines.ps1</c>.
/// Runtime use stays offline and deterministic; refresh tooling can rebuild the
/// cache from public route/segment datasets.
/// </summary>
public static class AirportAirlines
{
    private const string FixtureFileName = "airport-airlines.json.br";
    private const string UncompressedFixtureFileName = "airport-airlines.json";

    private static readonly ILogger Log = SimLog.CreateLogger("AirportAirlines");
    private static readonly Lazy<Data> _data = new(Load, LazyThreadSafetyMode.ExecutionAndPublication);

    public static int AirportCount => _data.Value.ByAirport.Count;

    public static string SourceDescription => _data.Value.SourceDescription;

    public static string PeriodStart => _data.Value.PeriodStart;

    public static string PeriodEnd => _data.Value.PeriodEnd;

    public static bool TryGetAirlinesForAirport(string airportId, [NotNullWhen(true)] out IReadOnlyList<AirportAirlineEntry>? airlines)
    {
        var normalized = NormalizeAirportId(airportId);
        if (normalized is null)
        {
            airlines = null;
            return false;
        }

        return _data.Value.ByAirport.TryGetValue(normalized, out airlines);
    }

    internal static string? NormalizeAirportId(string? airportId)
    {
        if (string.IsNullOrWhiteSpace(airportId))
        {
            return null;
        }

        var normalized = airportId.Trim().ToUpperInvariant();
        if (normalized.Length == 4 && (normalized[0] == 'K' || normalized[0] == 'P'))
        {
            return normalized[1..];
        }

        return normalized;
    }

    private static Data Load()
    {
        var path = FindFixturePath();
        if (path is null)
        {
            Log.LogWarning("{Fixture} not found; airport-airline map will be empty", FixtureFileName);
            return Data.Empty;
        }

        try
        {
            using var stream = OpenFixtureStream(path);
            var root = JsonSerializer.Deserialize<JsonRoot>(stream, JsonOptions);
            if (root is null)
            {
                Log.LogWarning("{Fixture} at {Path} deserialized to null; airport-airline map will be empty", FixtureFileName, path);
                return Data.Empty;
            }

            var byAirport = new Dictionary<string, IReadOnlyList<AirportAirlineEntry>>(StringComparer.OrdinalIgnoreCase);
            foreach (var (airportId, entry) in root.Airports ?? [])
            {
                var normalized = NormalizeAirportId(entry?.Iata ?? airportId);
                if (normalized is null)
                {
                    continue;
                }

                var airlines = (entry?.Airlines ?? [])
                    .Where(a => !string.IsNullOrWhiteSpace(a.Icao))
                    .Select(a => new AirportAirlineEntry(
                        a.Icao!.Trim().ToUpperInvariant(),
                        Math.Max(0, a.Arrivals),
                        Math.Max(0, a.Months),
                        a.Confidence ?? "unknown"
                    ))
                    .GroupBy(a => a.Icao, StringComparer.OrdinalIgnoreCase)
                    .Select(g => g.OrderByDescending(a => a.Arrivals).First())
                    .OrderByDescending(a => a.Arrivals)
                    .ThenBy(a => a.Icao, StringComparer.OrdinalIgnoreCase)
                    .ToArray();
                if (airlines.Length > 0)
                {
                    byAirport[normalized] = airlines;
                }
            }

            var metadata = root.Metadata;
            Log.LogInformation("Loaded airport-airline map for {AirportCount} airports from {Source}", byAirport.Count, metadata?.Source ?? path);

            return new Data(metadata?.Source ?? "", metadata?.PeriodStart ?? "", metadata?.PeriodEnd ?? "", byAirport);
        }
        catch (Exception ex)
        {
            Log.LogError(ex, "Failed to load airport-airline map from {Path}; map will be empty", path);
            return Data.Empty;
        }
    }

    private static string? FindFixturePath()
    {
        var baseDataDir = Path.Combine(AppContext.BaseDirectory, "Data");
        var candidates = new[]
        {
            Path.Combine(baseDataDir, FixtureFileName),
            Path.Combine(baseDataDir, UncompressedFixtureFileName),
            Path.Combine(AppContext.BaseDirectory, FixtureFileName),
            Path.Combine(AppContext.BaseDirectory, UncompressedFixtureFileName),
        };

        foreach (var candidate in candidates)
        {
            if (File.Exists(candidate))
            {
                return candidate;
            }
        }

        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (dir is not null)
        {
            var sourceDataDir = Path.Combine(dir.FullName, "src", "Yaat.Sim", "Data");
            foreach (var fileName in new[] { FixtureFileName, UncompressedFixtureFileName })
            {
                var candidate = Path.Combine(sourceDataDir, fileName);
                if (File.Exists(candidate))
                {
                    return candidate;
                }
            }

            dir = dir.Parent;
        }

        return null;
    }

    private static Stream OpenFixtureStream(string path)
    {
        var file = File.OpenRead(path);
        if (!path.EndsWith(".br", StringComparison.OrdinalIgnoreCase))
        {
            return file;
        }

        return new BrotliStream(file, CompressionMode.Decompress);
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        PropertyNameCaseInsensitive = true,
    };

    private sealed record Data(
        string SourceDescription,
        string PeriodStart,
        string PeriodEnd,
        IReadOnlyDictionary<string, IReadOnlyList<AirportAirlineEntry>> ByAirport
    )
    {
        public static readonly Data Empty = new("", "", "", new Dictionary<string, IReadOnlyList<AirportAirlineEntry>>());
    }

    private sealed class JsonRoot
    {
        public JsonMetadata? Metadata { get; set; }
        public Dictionary<string, JsonAirportEntry>? Airports { get; set; }
    }

    private sealed class JsonMetadata
    {
        public string? Source { get; set; }
        public string? PeriodStart { get; set; }
        public string? PeriodEnd { get; set; }
    }

    private sealed class JsonAirportEntry
    {
        public string? Iata { get; set; }
        public string? Icao { get; set; }
        public JsonAirlineEntry[]? Airlines { get; set; }
    }

    private sealed class JsonAirlineEntry
    {
        public string? Icao { get; set; }
        public int Arrivals { get; set; }
        public int Months { get; set; }
        public string? Confidence { get; set; }
    }
}

public sealed record AirportAirlineEntry(string Icao, int Arrivals, int Months, string Confidence);
