#!/usr/bin/env pwsh
# Migrate all v3 recording archives in TestData to v4 (deduplicated GroundLayout).
# Run from repo root: pwsh tools/migrate-recordings-v4.ps1
#
# Safe to run repeatedly — already-migrated v4 archives are skipped.
# Writes a temporary Yaat.Scratch/Program.cs, runs it, then restores the original.

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
if (-not (Test-Path "$repoRoot/yaat.slnx")) {
    $repoRoot = (git rev-parse --show-toplevel 2>$null)
    if (-not $repoRoot) {
        Write-Error "Run from the yaat repo root or a subdirectory."
        exit 1
    }
}

$scratchDir = Join-Path $repoRoot "tools/Yaat.Scratch"
$programCs = Join-Path $scratchDir "Program.cs"

# Back up current Program.cs
$backup = Get-Content -Path $programCs -Raw

$migrationCode = @'
// Auto-generated by tools/migrate-recordings-v4.ps1 — do not edit
using System.Text.Json;
using Yaat.Sim.Data.Airport;
using Yaat.Sim.Scenarios;
using Yaat.Sim.Simulation;
using Yaat.Sim.Simulation.Snapshots;

string testDataDir = args.Length > 0
    ? args[0]
    : Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "tests", "Yaat.Sim.Tests", "TestData"));

if (!Directory.Exists(testDataDir))
{
    Console.Error.WriteLine($"TestData directory not found: {testDataDir}");
    return 1;
}

var zips = Directory.GetFiles(testDataDir, "*.zip");
int migrated = 0;
int skipped = 0;

foreach (var zipPath in zips.OrderBy(f => f))
{
    string name = Path.GetFileName(zipPath);
    var originalSize = new FileInfo(zipPath).Length;

    RecordingManifest manifest;
    string scenarioJson;
    string? weatherJson;
    List<RecordedAction> actions;
    List<TimedSnapshot> timedSnapshots = [];
    var layouts = new Dictionary<string, AirportGroundLayout>(StringComparer.OrdinalIgnoreCase);

    try
    {
        using var sourceArchive = RecordingArchive.Open(zipPath);
        manifest = sourceArchive.Manifest;

        if (manifest.Version >= 4)
        {
            Console.WriteLine($"SKIP {name} (already v4)");
            skipped++;
            continue;
        }

        scenarioJson = sourceArchive.ReadScenarioJson();
        weatherJson = sourceArchive.ReadWeatherJson();
        actions = sourceArchive.ReadActions();

        for (int i = 0; i < manifest.Snapshots.Count; i++)
        {
            var timed = sourceArchive.ReadTimedSnapshot(i);
            timedSnapshots.Add(timed);

            if (layouts.Count == 0 && timed.State.Scenario.DelayedQueue is { Count: > 0 } queue)
            {
                foreach (var delayed in queue)
                {
                    var aircraft = JsonSerializer.Deserialize<LoadedAircraft>(delayed.AircraftJson, RecordingJsonOptions.Default);
                    if (aircraft?.State.GroundLayout is { } layout && !layouts.ContainsKey(layout.AirportId))
                    {
                        layouts[layout.AirportId] = layout;
                    }
                }
            }
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine($"SKIP {name} ({ex.Message})");
        skipped++;
        continue;
    }

    // Re-serialize delayed queues to strip [JsonIgnore] GroundLayout
    foreach (var timed in timedSnapshots)
    {
        if (timed.State.Scenario.DelayedQueue is { Count: > 0 } queue)
        {
            for (int j = 0; j < queue.Count; j++)
            {
                var old = queue[j];
                var aircraft = JsonSerializer.Deserialize<LoadedAircraft>(old.AircraftJson, RecordingJsonOptions.Default)!;
                var newJson = JsonSerializer.Serialize(aircraft, RecordingJsonOptions.Default);
                queue[j] = new DelayedSpawnDto { AircraftJson = newJson, SpawnAtSeconds = old.SpawnAtSeconds };
            }
        }
    }

    string tempPath = zipPath + ".v4.tmp";
    using (var outStream = File.Create(tempPath))
    using (var writer = new RecordingArchiveWriter(outStream))
    {
        writer.WriteScenario(scenarioJson);
        writer.WriteWeather(weatherJson);
        writer.WriteActions(actions);

        foreach (var layout in layouts.Values)
        {
            writer.WriteLayout(layout);
        }

        for (int i = 0; i < timedSnapshots.Count; i++)
        {
            var s = timedSnapshots[i];
            writer.WriteSnapshot(i, s.ElapsedSeconds, s.ActionIndex, s.State);
        }

        writer.Finish(
            manifest.ScenarioName,
            manifest.ScenarioId,
            manifest.ArtccId,
            manifest.RngSeed,
            manifest.TotalElapsedSeconds,
            manifest.RecordedAtUtc,
            manifest.RecordedBy
        );
    }

    var newSize = new FileInfo(tempPath).Length;
    File.Delete(zipPath);
    File.Move(tempPath, zipPath);

    double ratio = (1.0 - (double)newSize / originalSize) * 100;
    Console.WriteLine(
        $"OK   {name}: {layouts.Count} layout(s) [{string.Join(", ", layouts.Keys)}] "
        + $"{originalSize / 1024.0 / 1024.0:F1}MB -> {newSize / 1024.0 / 1024.0:F1}MB ({ratio:F0}% smaller)");
    migrated++;
}

Console.WriteLine($"\nDone. Migrated: {migrated}, Skipped: {skipped}");
return 0;
'@

try {
    Set-Content -Path $programCs -Value $migrationCode -NoNewline
    Write-Host "Running v3 -> v4 migration..."
    & dotnet run --project $scratchDir
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Migration failed with exit code $LASTEXITCODE"
        exit $LASTEXITCODE
    }
} finally {
    # Restore original Program.cs
    Set-Content -Path $programCs -Value $backup -NoNewline
    Write-Host "Restored Yaat.Scratch/Program.cs"
}
